name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  backend:
    name: Backend Lint & Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: |
          # Use optimized package.json without heavy dependencies
          cp package.ci.json package.json
          npm ci --prefer-offline --no-audit --no-fund

      - name: Lint (if present)
        run: |
          npm run lint --if-present || echo "lint script absent"

      - name: Format check (if present)
        run: |
          npm run format:check --if-present || npm run prettier:check --if-present || echo "format check absent"

  frontend:
    name: Frontend Lint & Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: Lint (if present)
        run: |
          npm run lint --if-present || echo "lint script absent"

      - name: Format check (if present)
        run: |
          npm run format:check --if-present || npm run prettier:check --if-present || echo "format check absent"
