name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build production image
        run: |
          docker build -f Dockerfile.prod -t batmodule:latest .
          docker tag batmodule:latest batmodule:${{ github.sha }}

      - name: Deploy notification
        run: |
          echo "🚀 Production deployment ready!"
          echo "Image: batmodule:${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
