name: Pull Request Checks

on:
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened]

jobs:
  pr-checks:
    name: PR Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check PR title
        run: |
          if [[ ! "${{ github.event.pull_request.title }}" =~ ^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+ ]]; then
            echo "❌ PR title must follow conventional commits format"
            echo "Format: type(scope): description"
            echo "Types: feat, fix, docs, style, refactor, test, chore"
            exit 1
          fi
          echo "✅ PR title follows conventional commits"

      - name: Check for breaking changes
        run: |
          if [[ "${{ github.event.pull_request.title }}" =~ BREAKING CHANGE ]]; then
            echo "⚠️ Breaking changes detected - ensure this is intentional"
          fi

      - name: Check PR size
        run: |
          FILES_CHANGED=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | wc -l)
          if [ $FILES_CHANGED -gt 50 ]; then
            echo "⚠️ Large PR detected ($FILES_CHANGED files changed)"
            echo "Consider breaking this into smaller PRs"
          else
            echo "✅ PR size is reasonable ($FILES_CHANGED files changed)"
          fi
