name: Pull Request Checks

on:
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened]

jobs:
  pr-checks:
    name: PR Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check PR title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR title: '$PR_TITLE'"
          
          # Simple validation: just check if title exists and is not too short
          if [ -z "$PR_TITLE" ]; then
            echo "❌ PR title cannot be empty"
            exit 1
          fi
          
          if [ ${#PR_TITLE} -lt 2 ]; then
            echo "❌ PR title is too short (minimum 2 characters)"
            exit 1
          fi
          
          echo "✅ PR title is valid"

      - name: Check for breaking changes
        run: |
          if [[ "${{ github.event.pull_request.title }}" =~ BREAKING CHANGE ]]; then
            echo "⚠️ Breaking changes detected - ensure this is intentional"
          fi

      - name: Check PR size
        run: |
          FILES_CHANGED=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | wc -l)
          if [ $FILES_CHANGED -gt 50 ]; then
            echo "⚠️ Large PR detected ($FILES_CHANGED files changed)"
            echo "Consider breaking this into smaller PRs"
          else
            echo "✅ PR size is reasonable ($FILES_CHANGED files changed)"
          fi
