name: Pull Request Checks

on:
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened]

jobs:
  pr-checks:
    name: PR Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check PR title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          # Allow conventional commits format OR simple descriptive titles for solo dev
          if [[ "$PR_TITLE" =~ ^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+ ]] || [[ "$PR_TITLE" =~ ^[A-Za-z0-9\s\-_]+$ ]]; then
            echo "✅ PR title is valid"
          else
            echo "❌ PR title should be descriptive or follow conventional commits format"
            echo "Conventional format: type(scope): description"
            echo "Simple format: descriptive title with letters, numbers, spaces, hyphens, underscores"
            echo "Current title: '$PR_TITLE'"
            exit 1
          fi

      - name: Check for breaking changes
        run: |
          if [[ "${{ github.event.pull_request.title }}" =~ BREAKING CHANGE ]]; then
            echo "⚠️ Breaking changes detected - ensure this is intentional"
          fi

      - name: Check PR size
        run: |
          FILES_CHANGED=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | wc -l)
          if [ $FILES_CHANGED -gt 50 ]; then
            echo "⚠️ Large PR detected ($FILES_CHANGED files changed)"
            echo "Consider breaking this into smaller PRs"
          else
            echo "✅ PR size is reasonable ($FILES_CHANGED files changed)"
          fi
